stages:
  #- pre-build
  - build
  #- test
  #- release
  #- deploy

variables:
  GIT_URL_HTTPS: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/aem.design/aemdesign-aem-prototype.git

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - node/

before_script:
  - echo $PATH
  - ls -latr /apps/maven/bin
  - export PATH=/apps/maven/bin:${PATH}
  - export PATH=/usr/lib/node_modules/yarn/bin:${PATH}
  - echo $PATH
  - which mvn
  - which yarn
  - which node
  - mvn -version
  - yarn --version
  - npm --version
  - git lfs install
  - git checkout master
  - git reset --hard "origin/master"
  - yarn install
  - ls -latr

test:
  stage: build
  image: aemdesign/centos-java-buildpack:latest
  script:
    - yarn aem:build
    - node content-generator/generator.js

