#!/bin/bash

# Check if Sync directory exists
if [ ! -d "sync/" ]; then
  echo Directory sync/ not found, run \"npm run aem:checkout\"vi a
  exit
fi

APPS_FOLDER=$(cat pom.xml | sed -n 's:.*<package\.appFolder>\(.*\)</package\.appFolder>.*:\1:p')
USERNAME=$(cat pom.xml | sed -n 's:.*<crx\.appFolder>\(.*\)</crx\.appFolder>.*:\1:p')
PASSWORD=$(cat pom.xml | sed -n 's:.*<crx\.password>\(.*\)</crx\.password>.*:\1:p')

echo Copying files from public to sync
cp -r public/ sync/jcr_root/apps/${APPS_FOLDER}/clientlibs

echo Launching VLT
cd sync && ../tools/vault-cli/bin/vlt --verbose --credentials ${USERNAME}:${PASSWORD} commit --force ./jcr_root/apps/${APPS_FOLDER}/clientlibs
