#!/bin/bash

# Check if the 'sync' directory exists
if [ -d "sync/" ]; then
  echo "Deleting current 'sync' folder..."
  rm -rf sync
fi

PORT=$(cat ../pom.xml | sed -n 's:.*<crx\.port>\(.*\)</crx\.port>.*:\1:p')
USERNAME=$(cat ../pom.xml | sed -n 's:.*<crx\.username>\(.*\)</crx\.username>.*:\1:p')
PASSWORD=$(cat ../pom.xml | sed -n 's:.*<crx\.password>\(.*\)</crx\.password>.*:\1:p')

echo "Syncing remote structure..."
./tools/vault-cli/bin/vlt --credentials ${USERNAME}:${PASSWORD} checkout --force --filter .maven/content/META-INF/vault/sync.xml http://localhost:${PORT}/crx ./sync
