content/_cq_tags/aemdesign/component-style-module: &component-style-module
  # Generic
  layout/button/navtoggler:
    flat: true
    prefix: navtoggler
    title: 'Nav Toggler (button)'

  # Carousel
  lists/carousel:
    flat: true
    prefix: carousel
    title: 'Carousel'

# Showcase Copy
content/_cq_tags/aemdesign-showcase/component-style-module: *component-style-module

# Training Copy
content/_cq_tags/aemdesign-training/component-style-module: *component-style-module
