content/_cq_tags/aemdesign/component-dialog: &component-dialog
  !!import/dirMerge component-dialog

# Showcase Copy
content/_cq_tags/aemdesign-showcase/component-dialog: *component-dialog

# Training Copy
content/_cq_tags/aemdesign-training/component-dialog: *component-dialog
