content/_cq_tags/aemdesign/component-style-modifier: &component-style-modifier

  # Backgrounds
  background/primary:
    prefixes:
      - charcoal
      - charcoal-pattern
      - red
      - red-pattern
      - red-50
      - yellow
      - yellow-pattern
      - yellow-50
    startWith: bg-
    title: '%%prefix_normalised%%'

  background/secondary:
    prefixes:
      - blue
      - blue-50
      - green
      - green-50
      - purple
      - purple-50
      - turquoise
      - turquoise-50
    startWith: bg-
    title: '%%prefix_normalised%%'

  background/greys:
    prefixes:
      - charcoal
      - grey-1
      - grey-2
      - grey-3
      - grey-4
      - grey-5
    startWith: bg-
    title: '%%prefix_normalised%%'

  background/standard:
    prefixes:
      - black
      - white
    startWith: bg-
    title: '%%prefix_normalised%%'

  # Button
  button:
      prefixes:
          - link
          - primary-red
          - primary-yellow
          - secondary-charcoal
          - secondary-outline
          - secondary-outline-charcoal
          - secondary-white
      valueFormat: btn btn-%%prefix%%
      title: '%%prefix_normalised%%'

  # Button
  button/normal:
    prefixes:
      - link
      - primary
      - secondary
      - success
      - danger
      - warning
      - info
      - light
      - dark
    valueFormat: btn btn-%%prefix%%
    title: '%%prefix_normalised%%'

  # Button Outlined
  button/outline:
    prefixes:
      - outline-primary
      - outline-secondary
      - outline-success
      - outline-danger
      - outline-warning
      - outline-info
      - outline-light
      - outline-dark
    valueFormat: btn btn-%%prefix%%
    title: '%%prefix_normalised%%'

  # Button Size
  button/size:
      contents:
          - block: { value: "btn-block", title: "Block (Full Width)" }
          - lg: { value: "btn-lg", title: "Large Button" }
          - sm: { value: "btn-sm", title: "Small Button" }

  # Button State
  button/state:
      contents:
          - active: { value: "active", title: "Active" }
          - disabled: { value: "disabled", title: "Disabled" }

  # Colours
  colour/primary:
    prefixes:
      - charcoal
      - red
      - red-50
      - yellow
      - yellow-50
    startWith: text-
    title: '%%prefix_normalised%%'

  colour/secondary:
    prefixes:
      - blue
      - blue-50
      - green
      - green-50
      - purple
      - purple-50
      - turquoise
      - turquoise-50
    startWith: text-
    title: '%%prefix_normalised%%'

  colour/greys:
    prefixes:
      - charcoal
      - grey-1
      - grey-2
      - grey-3
      - grey-4
      - grey-5
    startWith: text-
    title: '%%prefix_normalised%%'

  colour/standard:
    prefixes:
      - black
      - white
    startWith: text-
    title: '%%prefix_normalised%%'

  # Cards
  card:
    prefixes:
      - background
      - column
      - columns
      - notification
      - promoted
    valueFormat: card--%%prefix%%
    title: '%%prefix_normalised%%'

  # Embed
  embed/default:
    flat: true
    prefix: embed-responsive embed-responsive-1by1
    title: 'Default'

  embed/embed-responsive-1by1:
    flat: true
    prefix: embed-responsive embed-responsive-1by1
    title: 'Responsive 1 by 1'

  embed/embed-responsive-4by3:
    flat: true
    prefix: embed-responsive embed-responsive-4by3
    title: 'Responsive 4 by 3'

  embed/embed-responsive-16by9:
    flat: true
    prefix: embed-responsive embed-responsive-16by9
    title: 'Responsive 16 by 9'

  embed/embed-responsive-21by9:
    flat: true
    prefix: embed-responsive embed-responsive-21by9
    title: 'Responsive 21 by 9'

  # Flexbox
  flex/align-items:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - baseline
      - center
      - end
      - start
      - stretch
    valueFormat: 'align-items%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/align-self:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - baseline
      - center
      - end
      - start
      - stretch
    valueFormat: 'align-self%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/direction:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - row
      - row-reverse
      - column
      - column-reverse
    valueFormat: 'flex%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/justify-content:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - around
      - between
      - center
      - end
      - start
    valueFormat: 'justify-content%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  flex/order:
    breakpoints:
      - sm
      - md
      - lg
    sizes:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    prefix: order
    title: '%%sizeWithSuffix%% %%breakpoint%%'

  flex/wrap:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - nowrap
      - wrap
      - wrap-reverse
    valueFormat: 'flex%%infix%%-%%prefix%%'
    title: '%%prefix_normalised%% %%breakpoint%%'

  # Font
  font/weight:
    prefixes:
      - 300
      - 400
      - 600
      - 700
    valueFormat: 'fw-%%prefix%%'
    title: '%%prefix_normalised%%'

  # Grid
  grid/container:
    flat: true
    prefix: container
    title: 'Container'

  grid/container-flush:
    flat: true
    prefix: container-flush
    title: 'Container Flush'

  grid/container-text:
    flat: true
    prefix: container-text
    title: 'Container Text'

  # Icons
  icon/size:
    prefixes:
      - smaller
      - small
      - regular
      - large
    prefixValue: icon--
    title: '%%prefix_normalised%%'

  # Margin center
  margin/mx-auto:
    flat: true
    prefix: mx-auto
    title: 'Center Horizontally'

  # Text (Misc)
  text/list/colors:
    prefixes:
      - list-dark
    prefixValue: text-
    title: ' %%prefix_normalised%%'

  text/headings/style:
    prefixes:
      - heading-outlined
    prefixValue: text-
    title: 'No Underline'

  text/style:
    prefixes:
      - underlined
    prefixValue: text--
    title: 'Underlined'

  # Text Alignments
  text/alignment:
    breakpoints:
      - sm
      - md
      - lg
    prefixes:
      - center
      - left
      - right
    prefixValue: text-
    title: '%%prefix_normalised%% %%breakpoint%%'

  # Text transforms
  text/transform:
    prefixes:
      - capitalize
      - lowercase
      - none
      - uppercase
      - small
    prefixValue: text-
    title: '%%prefix_normalised%%'

  spacing/vertical:
    prefixes:
      - level-1
    prefixValue: spacing-vertical-
    title: '%%prefix_normalised%%'

  video:
    prefixes:
      - allowfullscreen
      - loop
      - mozAllowFullScreen
      - muted
      - playsinline
      - webkitallowfullscreen
    title: '%%prefix_normalised%%'

  visibility/hide:
    prefixes:
      - invisible
      - invisible-lg-down
      - invisible-lg-up
      - invisible-md-down
      - invisible-md-up
      - invisible-sm-down
      - invisible-sm-up
      - invisible-xl-down
      - invisible-xl-up
      - invisible-xs-down
      - invisible-xs-up
    title: '%%prefix_normalised%%'

  visibility/screen-reader:
    prefixes:
      - sr-only
      - sr-only-focusable
      - text-hide
      - visible
    title: '%%prefix_normalised%%'

  schema/widgets/onlinemedia:
    contents:
    - video: { value: "itemscope itemtype=&quot;http://schema.org/VideoObject&quot;", title: "Video Object" }

  schema/details/eventdetails:
    contents:
    - event: { value: "itemscope itemtype=&quot;http://schema.org/Event&quot;", title: "Event Object" }

  schema/details/contactdetails:
    contents:
    - person: { value: "itemscope itemtype=&quot;http://schema.org/Person&quot;", title: "Person Object" }

  height:
    contents:
      - banner: {title: "Banner H:200px", value: "height-banner"}

# Showcase Copy
content/_cq_tags/aemdesign-showcase/component-style-modifier: *component-style-modifier

# Training Copy
content/_cq_tags/aemdesign-training/component-style-modifier: *component-style-modifier
