content/_cq_tags/aemdesign/component-style-modifier: &component-style-modifier
  !!import/merge
    - component-style-modifier

# Showcase Copy
content/_cq_tags/aemdesign-showcase/component-style-modifier: *component-style-modifier

# Training Copy
content/_cq_tags/aemdesign-training/component-style-modifier: *component-style-modifier
