# Themes
content/_cq_tags/aemdesign/component-style-theme: &component-style-theme
  !!import/dirMerge component-style-theme

# Showcase Copy
content/_cq_tags/aemdesign-showcase/component-style-theme: *component-style-theme

# Training Copy
content/_cq_tags/aemdesign-training/component-style-theme: *component-style-theme
