
# Content Type
content/_cq_tags/aemdesign/content-type: &content-type
  !!import/merge
    - content-type

# Showcase Copy
content/_cq_tags/aemdesign-showcase/content-type: *content-type

# Training Copy
content/_cq_tags/aemdesign-training/content-type: *content-type
