#!/bin/bash

POM_FILE="../pom.xml"
PARENT_PROJECT_PATH="$(realpath ..)"
SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

set_term_title "Core Package"

set_term_title "Packaging Monolith Package: mvn -Dvault.useProxy=false -DskipTests -e -U clean package "
echo "- Package"
mvn -Dvault.useProxy=false -DskipTests -e -U clean package "$@"
set_term_title "Packaged"
