---
## file: site.yml
## This playbook deploys the whole application stack.

- name: site automation testing
  hosts: 127.0.0.1
  connection: local

  pre_tasks:
    - name: get docker host ip
      shell: |
        set -o pipefail
        NETWORK_INTERFACE=$(route -n get 0.0.0.0 2>/dev/null | awk '/interface: / {print $2}')
        ifconfig $NETWORK_INTERFACE | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | head -1
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false
    - name: set params
      set_fact:
        test_debug_hide: "false"
        service_aem_license_key: "{{ lookup('env','AEM_KEY') }}"
        service_aem_license_name: "{{ lookup('env','AEM_NAME') }}"
        service_aem_access_host: "localhost"
        service_aem_username: "admin"
        service_aem_password: "admin"
        service_aem_container_name: "service_aem_container_name"
        service_selenium_node_name_chrome: "service_selenium_node_name_chrome"
        service_selenium_grid_container_name: "service_selenium_grid_container_name"
        service_docker_host: "unix://var/run/docker.sock"
        service_docker_host_address: "{{ dockerhost_ip.stdout }}"


  tasks:
    - name: run selenium grid
      import_role:
        name: aem_design.selenium_grid
      vars:
        grid_host: "{{ service_docker_host_address }}"
        grid_http_port: "{{ service_selenium_grid_port }}"
        docker_image: "selenium/hub"
        docker_image_tag: "latest"
        docker_container_name: "{{ service_selenium_grid_container_name }}"
        docker_host: "{{ service_docker_host }}"
        docker_volumes: []
        docker_published_ports: [
          "{{ service_selenium_grid_port }}:4444",
        ]
        debug_hide: "{{ test_debug_hide }}"
    - name: run selenium grid node chrome
      import_role:
        name: aem_design.selenium_grid_node
      vars:
        grid_host: "{{ service_docker_host_address }}"
        grid_port: "{{ service_selenium_grid_port }}"
        docker_image: "selenium/node-chrome"
        docker_image_tag: "latest"
        docker_container_name: "{{ service_selenium_node_name_chrome }}"
        docker_host: "{{ service_docker_host }}"
        docker_published_ports: []
        debug_hide: "{{ test_debug_hide }}"
    - name: run aem author istance
      import_role:
        name: aem_design.aem
      vars:
        docker_published_ports: [
          "{{ service_aem_access_port }}:8080"
        ]
        docker_volumes: []
        docker_container_name: "{{ service_aem_container_name }}"
        docker_image: "aemdesign/aem"
        docker_image_tag: "6.5.0-bundle"
        docker_host: "{{ service_docker_host }}"
        debug_hide: "{{ test_debug_hide }}"
        aem_jvm_opts: "-server -Xms248m -Xmx1524m \
          -XX:MaxDirectMemorySize=256M \
          -XX:+CMSClassUnloadingEnabled \
          -Djava.awt.headless=true \
          -Dorg.apache.felix.http.host=0.0.0.0"
    - name: ensure container is registered
      import_role:
        name: aem_design.aem_license
      vars:
        aem_license_key: "{{ service_aem_license_key }}"
        aem_license_name: "{{ service_aem_license_name }}"
        aem_port: "{{ service_aem_access_port }}"
        aem_host: "{{ service_aem_access_host }}"
        docker_host: "{{ service_docker_host }}"
        debug_hide: "{{ test_debug_hide }}"
        wait_delay: 10
    - name: ensure instance is ready
      import_role:
        name: aem_design.aem_verify
      vars:
        aem_port: "{{ service_aem_access_port }}"
        aem_host: "{{ service_aem_access_host }}"
        docker_host: "{{ service_docker_host }}"
        debug_hide: "{{ test_debug_hide }}"
    - name: install showcase package
      command: "curl -u {{ service_aem_username }}:{{ service_aem_password }} \
        -F 'file=@{{ package_file }}' \
        -F 'name={{ package_filename }}' \
        -F force=true \
        -F install=true \
        'http://{{ service_docker_host_address }}:{{ service_aem_access_port }}/crx/packmgr/service.jsp'"



