version: "3.8"

services:

  author:
    image: aemdesign/aem:sdk-2022.4.7138
    hostname: author
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 localhost:${AUTHOR_PORT_INTERNAL}/system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 1s
    ports:
      - ${AUTHOR_PORT}:${AUTHOR_PORT_INTERNAL}
      - ${AUTHOR_PORT_DEBUG}:${AUTHOR_PORT_INTERNAL_DEBUG}
    environment:
      - TZ=${GLOBAL_TZ}
      - AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,localdev
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=${AUTHOR_PORT_INTERNAL_DEBUG},suspend=n
    labels:
      # note that you want this frontened to match the last. otherwise it will match login.${HOST_DOMAIN}"
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.author.rule: "Host(`${AUTHOR_HOST}`)"
      traefik.http.routers.author.entrypoints: web
      traefik.http.routers.author_https.rule: "Host(`${AUTHOR_HOST}`)"
      traefik.http.routers.author_https.tls: true
      traefik.http.routers.author_https.entrypoints: websecure
      traefik.http.services.author.loadbalancer.passHostHeader: true
      traefik.http.services.author.loadbalancer.server.port: ${AUTHOR_PORT_INTERNAL}
    volumes:
      - author-data:/aem/crx-quickstart/repository
    networks:
      internal:
        aliases:
          - ${AUTHOR_SUBDOMAIN_NAME}
          - ${AUTHOR_HOST}


  author-deploy-core:
    image: aemdesign/java-buildpack:jdk11
    hostname: author-deploy-core
    command:
      - bash
      - -l
      - -c
      - "cd /build/source/aemdesign-aem-core && mvn -DskipTests -e -U -P autoInstallPackage clean install -Daem.port=${AUTHOR_PORT_INTERNAL} -Daem.host=${AUTHOR_SUBDOMAIN_NAME} -Dmaven.repo.local=/build/.m2/repository"
    working_dir: "/build/source"
    volumes:
      - "./:/build/source"
      - "~/.m2:/build/.m2"
    networks:
      - internal

  author-deploy-support:
    image: aemdesign/java-buildpack:jdk11
    hostname: author-deploy-support
    command:
      - bash
      - -l
      - -c
      - "cd /build/source/aemdesign-aem-support && mvn -DskipTests -e -U -P autoInstallPackage clean install -Daem.port=${AUTHOR_PORT_INTERNAL} -Daem.host=${AUTHOR_SUBDOMAIN_NAME} -Dmaven.repo.local=/build/.m2/repository"
    working_dir: "/build/source"
    volumes:
      - "./:/build/source"
      - "~/.m2:/build/.m2"
    networks:
      - internal

  publish:
    image: aemdesign/aem:sdk-2022.4.7138
    hostname: publish
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 localhost:${PUBLISH_PORT_INTERNAL}/system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
    ports:
      - ${PUBLISH_PORT}:${PUBLISH_PORT_INTERNAL}
      - ${PUBLISH_PORT_DEBUG}:${PUBLISH_PORT_INTERNAL_DEBUG}
    environment:
      - TZ=${GLOBAL_TZ}
      - AEM_RUNMODE=-Dsling.run.modes=publish,crx3,crx3tar,localdev
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=${PUBLISH_PORT_INTERNAL_DEBUG},suspend=n
    labels:
      # note that you want this frontened to match the last. otherwise it will match login.${HOST_DOMAIN}"
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.publish.rule: "Host(`${PUBLISH_HOST}`)"
      traefik.http.routers.publish.entrypoints: web
      traefik.http.routers.publish_https.rule: "Host(`${PUBLISH_HOST}`)"
      traefik.http.routers.publish_https.tls: true
      traefik.http.routers.publish_https.entrypoints: websecure
      traefik.http.services.publish.loadbalancer.passHostHeader: true
      traefik.http.services.publish.loadbalancer.server.port: ${PUBLISH_PORT_INTERNAL}
    volumes:
      - publish-data:/aem/crx-quickstart/repository
    networks:
      internal:
        aliases:
          - ${PUBLISH_SUBDOMAIN_NAME}
          - ${PUBLISH_HOST}

  publish-deploy-core:
    image: aemdesign/java-buildpack:jdk11
    hostname: publishdeploy
    command:
      - bash
      - -l
      - -c
      - "cd /build/source/aemdesign-aem-core && mvn -DskipTests -e -U -P autoInstallPackage clean install -Daem.port=${PUBLISH_PORT_INTERNAL} -Daem.host=${PUBLISH_SUBDOMAIN_NAME} -Dmaven.repo.local=/build/.m2/repository"
    working_dir: "/build/source"
    volumes:
      - "./:/build/source"
      - "~/.m2:/build/.m2"
    networks:
      - internal

  publish-deploy-support:
    image: aemdesign/java-buildpack:jdk11
    hostname: publishdeploy
    command:
      - bash
      - -l
      - -c
      - "cd /build/source/aemdesign-aem-support && mvn -DskipTests -e -U -P autoInstallPackage clean install -Daem.port=${PUBLISH_PORT_INTERNAL} -Daem.host=${PUBLISH_SUBDOMAIN_NAME} -Dmaven.repo.local=/build/.m2/repository"
    working_dir: "/build/source"
    volumes:
      - "./:/build/source"
      - "~/.m2:/build/.m2"
    networks:
      - internal

  dispatcher:
    image: aemdesign/dispatcher
    hostname: dispatcher
    ports:
      - ${DISPATCHER_PORT}:${DISPATCHER_PORT_INTERNAL}
      - ${DISPATCHER_PORT_SSL}:8433
    environment:
      - RENDERER_PORT=${PUBLISH_PORT_INTERNAL}
      - RENDERER_HOST=${PUBLISH_SUBDOMAIN_NAME}
      - DISPATCHER_CONFIG=${PUBLISH_SUBDOMAIN_NAME}
    labels:
      # note that you want this frontened to match the last. otherwise it will match login.${HOST_DOMAIN}"
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.dispatcher.rule: "Host(`${DISPATCHER_HOST}`)"
      traefik.http.routers.dispatcher.entrypoints: web
      traefik.http.routers.dispatcher_https.rule: "Host(`${DISPATCHER_HOST}`)"
      traefik.http.routers.dispatcher_https.tls: true
      traefik.http.routers.dispatcher_https.entrypoints: websecure
      traefik.http.services.dispatcher.loadbalancer.passHostHeader: true
      traefik.http.services.publish.loadbalancer.server.port: ${DISPATCHER_PORT_INTERNAL}

    volumes:
      - dispatcher-data:/data/httpd/cache
    networks:
      internal:
        aliases:
          - ${DISPATCHER_SUBDOMAIN_NAME}
          - ${DISPATCHER_HOST}

networks:
  internal:

volumes:
  author-data:
  publish-data:
  dispatcher-data:
