---
# vars file for .

aem_license_key: ""                                                       # license key submit value
aem_license_name: "company"                                                      # company name submit value
aem_license_path: "/system/granite/license/index.html"                    # license page path
aem_license_console_path: "/system/console/productinfo"                   # license console path, used to check if license worked
aem_license_eula: "on"                                                    # eula submit value
aem_license_post_eula: "eula"                                             # eula checkbox field name
aem_license_post_name: "name"                                             # company name field name
aem_license_post_key: "id"                                                # key field name

aem_port: "4502"                                                          # aem service port
aem_host: "localhost"                                                     # aem service host
aem_username: "admin"
aem_password: "admin"

wait_delay: 1                                                             # how long to wait between retries
wait_timeout: 300                                                         # how long to wait before terminating
wait_retries: 360                                                         # how many times to retry waiting

license_page_test: "I have read and accept the End User License Agreement"   # string to search for in license page to verify that its actual license page
license_page_test_error_license: "markField('license');"                     # string to search for in license page to check if error is with license
license_page_test_error_name: "markField('name');"                      # string to search for in license page to check if error is with key
license_console_test_nolicense: "No License configured"                  # string to search for in license console page to verify that license does not exist
license_console_test_ready: "Installed Products"                           # string to search for in license console page to verify that license console is ready
