version: "2.4"

services:

  testing:
    image: aemdesign/centos-java-buildpack:jdk11
    hostname: testing
    environment:
      # maven
      - MAVEN_COMMAND=bash ./test-spec --host author --port 8080 --url http://seleniumhub:4444 --maven
      # docker
      - PARENT_PROJECT_WITH_GIT=.
      - PARENT_PROJECT_WITH_GIT_NAME=geb-aem-testing
      - CURRENT_PROJECT_LOCATION=geb-aem-testing/gebaemtesting-testing
    command: "bash -c -l 'cd /build/$${CURRENT_PROJECT_LOCATION}; $${MAVEN_COMMAND}'"
    working_dir: "/build/geb-aem-testing/gebaemtesting-testing/"
    volumes:
      - ./:/build/geb-aem-testing
      - ~/.m2:/build/.m2
    networks:
      - default
      - seleniumgrid
      - author-network
      - publish-network
      - dispatcher-network

  testingprep:
    image: aemdesign/ansible-playbook
    hostname: testingprep
    environment:
      aem_port: 4502
      aem_host: author
      aem_username: admin
      aem_password: admin
    command:
      - bash
      - -l
      - -c
      - "pwd && ls -l && ansible-galaxy install -r requirements.yml && ansible-playbook testingprep.yml --extra-vars debug_hide=true"
    volumes:
      - ./playbooks:/ansible/playbooks
    networks:
      - seleniumgrid
      - author-network
      - publish-network
      - dispatcher-network
      - default

  testingcheck:
    image: docker
    hostname: testingcheck
    working_dir: "/build"
    volumes:
      - ../../:/build
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./scripts/gettestresult.sh:/test.sh
    command:
      - sh
      - /test.sh

networks:
  seleniumgrid:
  author-network:
  publish-network:
  dispatcher-network:
