version: "2.4"

services:

  nginx:
    image: nginx
    restart: always
    extends:
      file: ../common/config-tz.yml
      service: config
    working_dir: /content
    hostname: "nginx"
    labels:
      - "traefik.frontend.priority=1"
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=PathPrefix(`/`)"
      - "traefik.http.routers.www.entrypoints=web"
      - "traefik.http.routers.www_https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.www_https.tls=true"
      - "traefik.http.routers.www_https.entrypoints=websecure"
    volumes:
      - ./content:/content
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

networks:
  internal:

volumes:
  data:
