apps/aemdesign/global/dialog/touch/text/content/items/textTab/items/column/items/text/rtePlugins: &global-dialog-text-rtePlugins
  misctools/specialCharsConfig/chars: &global-dialog-text-rtePlugins-misctools-specialCharsConfig-chars
    template: 'text-misctools-specialCharsConfig-chars'
    contents:
      - default_copyright: { entity: '&amp;copy;', name: "copyright" }
      - default_euro: { entity: '&amp;euro;', name: "euro" }
      - default_registered: { entity: '&amp;reg;', name: "registered" }
      - default_trademark: { entity: '&amp;trade;', name: "trademark" }

  styles/styles: &global-dialog-text-rtePlugins-styles-styles
    template: 'text-rtePlugins-styles-styles'
    contents:
      - font_weight_lighter: { cssName: 'font-weight-lighter', text: "Weight: Lighter" }
      - font_weight_light: { cssName: 'font-weight-light', text: "Weight: Light" }
      - font_weight_normal: { cssName: 'font-weight-normal', text: "Weight: Normal" }
      - font_weight_bold: { cssName: 'font-weight-bold', text: "Weight: Bold" }
      - font_weight_bolder: { cssName: 'font-weight-bolder', text: "Weight: Bolder" }
      - text_quote_suffix: { cssName: 'text__quote-suffix', text: "Style: Quote Suffix" }
      - text_style_lead: { cssName: 'lead', text: "Style: Lead" }
      - text_black: { cssName: 'text-black', text: "Colour: Black" }
      - text_white: { cssName: 'text-white', text: "Colour: White" }

  paraformat/formats: &global-dialog-text-rtePlugins-paraformat-formats
    template: 'text-rtePlugins-paraformat-formats'
    contents:
      - default_blockquote: { description: 'Block Quote', tag: "blockquote" }
      - default_emphasis: { description: 'Emphasis', tag: "em" }
      - default_h1: { description: 'Heading 1', tag: "h1" }
      - default_h2: { description: 'Heading 2', tag: "h2" }
      - default_h3: { description: 'Heading 3', tag: "h3" }
      - default_h4: { description: 'Heading 4', tag: "h4" }
      - default_h5: { description: 'Heading 5', tag: "h5" }
      - default_h6: { description: 'Heading 6', tag: "h6" }
      - default_p: { description: 'Paragraph', tag: "p" }
      - default_small: { description: 'Small', tag: "small" }

# AEM Design global configuration
apps/aemdesign/global/dialog/touch/description/content/items/descriptionTab/items/column/items/description/rtePlugins: *global-dialog-text-rtePlugins

apps/aemdesign/global/dialog/touch/table/content/items/tableTab/items/column/items/table/rtePlugins: &global-dialog-table-rtePlugins
  misctools/specialCharsConfig/chars: *global-dialog-text-rtePlugins-misctools-specialCharsConfig-chars
  styles/styles: *global-dialog-text-rtePlugins-styles-styles
  paraformat/formats: *global-dialog-text-rtePlugins-paraformat-formats
