---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
  inventory:
    group_vars:
      all:
        service_aem_license_key: "${AEM_KEY}"
        service_aem_license_name: "${AEM_NAME}"
        role_name: "${ROLE_NAME_FULL}"
platforms:
  - name: instance
    image: "aemdesign/ansible-playbook:${MOLECULE_DISTRO:-centos7}"
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/lib/systemd/systemd"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/tmp/docker.sock
    privileged: true
    pre_build_image: true
  - name: aemtest
    image: "aemdesign/aem:6.5.0"
    command: ""
    published_ports:
      - 5502:8080
    env:
      TZ: "Australia/Sydney"
      AEM_JVM_OPTS:
        -server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true
        -Dorg.apache.felix.http.host=0.0.0.0"
      AEM_RUNMODE: "-Dsling.run.modes=author,crx3,crx3tar,dev"
    pre_build_image: true
    privileged: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
