---
extends: default
rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments: enable
  comments-indentation: enable
  document-start: enable
  empty-lines:
    max: 3
    level: error
  hyphens:
    level: error
  indentation: enable
  key-duplicates: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  trailing-spaces: enable
  truthy: enable
  line-length:
    max: 200
    level: warning
