#!/bin/bash

PARENT_PROJECT_PATH="$(realpath ..)"

SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

$DOCKER stop selenium-hub

$DOCKER stop selenium-hub-node-chrome
#docker stop selenium-hub-node-firefox

$DOCKER network rm selenium-grid
