---
language: python
services: docker

env:
  global:
    - ROLE_META: "meta/main.yml"
  matrix:
    - MOLECULE_DISTRO: centos7
#    - MOLECULE_DISTRO: ubuntu1804
#    - MOLECULE_DISTRO: ubuntu1604
#    - MOLECULE_DISTRO: ubuntu1404
#    - MOLECULE_DISTRO: debian9
#    - MOLECULE_DISTRO: fedora27

before_install:
  # Read role from meta.yml and replace '-' with '_' to be Ansible friendly
  - export ROLE_REPO_NAME=$(grep "role_name:" ${ROLE_META} | sed -e "s/.*role_name.* \(.*\)/\1/")
  - export ROLE_NAME=$(grep "role_name:" ${ROLE_META} | sed -e "s/.*role_name.* \(.*\)/\1/" | sed "s/-/_/g")
  - export ROLE_NAMESPACE=$(grep "company:" ${ROLE_META} | sed -e "s/.*company.* \(.*\)/\1/" | sed "s/\./_/g")
  # Store Ansible friendly role name to use in molecule.yml
  - export ROLE_NAME_FULL=$ROLE_NAMESPACE.$ROLE_NAME
  - echo ROLE_REPO_NAME=${ROLE_REPO_NAME}
  - echo ROLE_NAME=${ROLE_NAME}
  - echo ROLE_NAMESPACE=${ROLE_NAMESPACE}
  - echo ROLE_NAME_FULL=${ROLE_NAME_FULL}


install:
  # Install test dependencies.
  - pip install testinfra molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_REPO_NAME $ROLE_NAME_FULL
  - cd $ROLE_NAME_FULL

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
