
# Online Media
content-type/widgets/onlinemedia/provider/default:
  flat: true
  prefix: default
  title: 'Default'

content-type/widgets/onlinemedia/provider/kaltura:
  flat: true
  prefix: kaltura
  title: 'Kaltura'

content-type/widgets/onlinemedia/provider/youtube:
  flat: true
  prefix: youtube
  title: 'Youtube'

