components/lists/list/orderby:
  contents:
    - bytitle: {
      title: "By Title",
      value: "@jcr:content/jcr:title"
    }
    - bycreated: {
      title: "By Created Date",
      value: "@jcr:content/jcr:created"
    }
    - bymodified: {
      title: "By Modified Date",
      value: "@jcr:content/jcr:lastModified"
    }
    - bytemplate: {
      title: "By Template",
      value: "@jcr:content/jcr:template"
    }
    - byscore: {
      title: "By Score",
      value: "@jcr:score"
    }
    - bypublishdate: {
      title: "By Publish Date",
      value: "@jcr:content/*/par/*/publishDate"
    }

components/lists/list/badge:
  contents:
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }
    - cardIcon: {
      title: "Card with Icon",
      value: "cardIcon"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - cardIconTitleCategoryDescription: {
      title: "Card with Icon, Title, Category and Description",
      value: "cardIconTitleCategoryDescription"
    }
    - cardImageTitleCategoryDescription: {
      title: "Card with Image, Title, Category and Description",
      value: "cardImageTitleCategoryDescription"
    }
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }

components/lists/pagelist/badge:
  contents:
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }
    - cardIcon: {
      title: "Card with Icon",
      value: "cardIcon"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - cardIconTitleCategoryDescription: {
      title: "Card with Icon, Title, Category and Description",
      value: "cardIconTitleCategoryDescription"
    }
    - cardImageTitleCategoryDescription: {
      title: "Card with Image, Title, Category and Description",
      value: "cardImageTitleCategoryDescription"
    }
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardTitleDescriptionAction: {
      title: "Card with Title, Description and Action",
      value: "cardTitleDescriptionAction"
    }
    - cardImageTitleSubtitleDescriptionAction: {
      title: "Card with Image, Title, Sub Title, Description and Action",
      value: "cardImageTitleSubtitleDescriptionAction"
    }
    - cardImageTitleDescriptionAction: {
      title: "Card with Image, Title, Description and Action",
      value: "cardImageTitleDescriptionAction"
    }
    - cardImageTitleAction: {
      title: "Card with Image, Title and Action",
      value: "cardImageTitleAction"
    }
    - cardImageTitleDescription: {
      title: "Card with Image, Title and Description",
      value: "cardImageTitleDescription"
    }
    - cardImageTagTitleAction: {
      title: "Card with Image, Tag, Title and Action",
      value: "cardImageTagTitleAction"
    }
    - cardIconDescription: {
      title: "Card with Icon and Description",
      value: "cardIconDescription"
    }
    - cardIconTitle: {
      title: "Card with Icon and Title",
      value: "cardIconTitle"
    }
    - cardIconTitleDescription: {
      title: "Card with Icon, Title and Description",
      value: "cardIconTitleDescription"
    }
    - cardIconTitleDescriptionAction: {
      title: "Card with Icon, Title, Description and Action",
      value: "cardIconTitleDescriptionAction"
    }
    - cardImageSubtitleTitleCategoryDescriptionAction: {
      title: "Clickable Card with Image, Subtitle, Title, Category, Description and Action",
      value: "cardImageSubtitleTitleCategoryDescriptionAction"
    }
    - cardActionImageTitle: {
      title: "Clickable Card with Image and Title",
      value: "cardActionImageTitle"
    }
    - cardActionIconTitleCategoryDescription: {
      title: "Clickable Card with Icon, Title, Category and Description",
      value: "cardActionIconTitleCategoryDescription"
    }
    - cardActionImageTitleDescription: {
      title: "Clickable Card with Image, Title and Description",
      value: "cardActionImageTitleDescription"
    }
    - cardActionIconDescription: {
      title: "Clickable Card with Icon and Description",
      value: "cardActionIconDescription"
    }
    - cardActionImageTitleCategoryDescription: {
      title: "Clickable Card with Image, Title, Category and Description",
      value: "cardActionImageTitleCategoryDescription"
    }
    - cardActionIconTitleDescription: {
      title: "Clickable Card with Icon, Title and Description",
      value: "cardActionIconTitleDescription"
    }

components/lists/newslist/badge:
  contents:
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }
    - cardIcon: {
      title: "Card with Icon",
      value: "cardIcon"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - cardIconTitleCategoryDescription: {
      title: "Card with Icon, Title, Category and Description",
      value: "cardIconTitleCategoryDescription"
    }
    - cardImageTitleCategoryDescription: {
      title: "Card with Image, Title, Category and Description",
      value: "cardImageTitleCategoryDescription"
    }
    - cardImageTitleCategoryActionDate: {
      title: "Card with Image, Title, Category, Action and Date",
      value: "cardImageTitleCategoryActionDate"
    }
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardTitleDescriptionAction: {
      title: "Card with Title, Description and Action",
      value: "cardTitleDescriptionAction"
    }
    - cardImageTitleSubtitleDescriptionAction: {
      title: "Card with Image, Title, Sub Title, Description and Action",
      value: "cardImageTitleSubtitleDescriptionAction"
    }
    - cardImageTitleDescriptionAction: {
      title: "Card with Image, Title, Description and Action",
      value: "cardImageTitleDescriptionAction"
    }
    - cardImageTitleAction: {
      title: "Card with Image, Title and Action",
      value: "cardImageTitleAction"
    }
    - cardImageTitleDescription: {
      title: "Card with Image, Title and Description",
      value: "cardImageTitleDescription"
    }
    - cardIconDescription: {
      title: "Card with Icon and Description",
      value: "cardIconDescription"
    }
    - cardIconTitleDescription: {
      title: "Card with Icon, Title and Description",
      value: "cardIconTitleDescription"
    }
    - cardIconTitleDescriptionAction: {
      title: "Card with Icon, Title, Description and Action",
      value: "cardIconTitleDescriptionAction"
    }
    - cardActionImageTitle: {
      title: "Clickable Card with Image and Title",
      value: "cardActionImageTitle"
    }
    - cardActionIconTitleCategoryDescription: {
      title: "Clickable Card with Icon, Title, Category and Description",
      value: "cardActionIconTitleCategoryDescription"
    }
    - cardActionImageTitleDescription: {
      title: "Clickable Card with Image, Title and Description",
      value: "cardActionImageTitleDescription"
    }
    - cardActionIconDescription: {
      title: "Clickable Card with Icon and Description",
      value: "cardActionIconDescription"
    }
    - cardActionImageTitleCategoryDescription: {
      title: "Clickable Card with Image, Title, Category and Description",
      value: "cardActionImageTitleCategoryDescription"
    }
    - cardActionIconTitleDescription: {
      title: "Clickable Card with Icon, Title and Description",
      value: "cardActionIconTitleDescription"
    }

components/lists/eventlist/badge:
  contents:
    - cardActionIconTitleCategoryDescription: {
      title: "Clickable Card with Icon, Title, Category and Description",
      value: "cardActionIconTitleCategoryDescription"
    }
    - cardActionImageTitle: {
      title: "Clickable Card with Image and Title",
      value: "cardActionImageTitle"
    }
    - cardActionImageTitleCategoryDescription: {
      title: "Clickable Card with Image, Title, Category and Description",
      value: "cardActionImageTitleCategoryDescription"
    }
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardIcon: {
      title: "Card with Icon",
      value: "cardIcon"
    }
    - cardIconTitleAction: {
      title: "Card with Icon, Title and Action",
      value: "cardIconTitleAction"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardIconTitleDateAction: {
      title: "Card with Icon, Title, Date and Action",
      value: "cardIconTitleDateAction"
    }
    - cardIconTitleDescriptionAction: {
      title: "Card with Icon, Title, Description and Action",
      value: "cardIconTitleDescriptionAction"
    }
    - cardIconTitleSubtitleDate: {
      title: "Card with Icon, Title, Subtitle and Date",
      value: "cardIconTitleSubtitleDate"
    }
    - cardIconTitleSubtitleDateDescriptionAction: {
      title: "Card with Icon, Title, Subtitle, Date, Description and Action",
      value: "cardIconTitleSubtitleDateDescriptionAction"
    }
    - cardIconTitleSubtitleDescriptionAction: {
      title: "Card with Icon, Title, Subtitle, Description and Action",
      value: "cardIconTitleSubtitleDescriptionAction"
    }
    - cardImageTitleAction: {
      title: "Card with Image, Title and Action",
      value: "cardImageTitleAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - cardImageTitleDescriptionAction: {
      title: "Card with Image, Title, Description and Action",
      value: "cardImageTitleDescriptionAction"
    }
    - cardImageTitleSubtitleDescriptionAction: {
      title: "Card with Image, Title, Sub Title, Description and Action",
      value: "cardImageTitleSubtitleDescriptionAction"
    }
    - cardTitleDescriptionAction: {
      title: "Card with Title, Description and Action",
      value: "cardTitleDescriptionAction"
    }
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }

components/lists/contactlist/badge:
  contents:
    - cardActionIconTitleCategoryDescription: {
      title: "Clickable Card with Icon, Title, Category and Description",
      value: "cardActionIconTitleCategoryDescription"
    }
    - cardActionImageTitleCategoryDescription: {
      title: "Clickable Card with Image, Title, Category and Description",
      value: "cardActionImageTitleCategoryDescription"
    }
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardIcon: {
      title: "Card with Icon",
      value: "cardIcon"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }

components/lists/locationlist/badge:
  contents:
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardIconTitleCategoryDescription: {
      title: "Card with Icon, Title, Category and Description",
      value: "cardIconTitleCategoryDescription"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescription: {
      title: "Card with Image, Title, Category and Description",
      value: "cardImageTitleCategoryDescription"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
    - data: {
      title: "Output Data",
      value: "data"
    }
    - icon: {
      title: "Icon",
      value: "icon"
    }
    - image: {
      title: "Image",
      value: "image"
    }

components/lists/navlist/variant:
  contents:
    - simple: {
      title: "Simple",
      value: "simple"
    }
    - stacked: {
      title: "Stacked",
      value: "stacked"
    }
    - dropdown: {
      title: "Dropdown",
      value: "dropdown"
    }

components/lists/taglist/orderby:
  contents:
    - byscore: {
      title: "By Score",
      value: "@jcr:score"
    }
    - bytitle: {
      title: "By Title",
      value: "@jcr:content/jcr:title"
    }

components/lists/taglist/variant:
  contents:
    - optionsList: {
      title: "Options List",
      value: "optionsList"
    }
    - list: {
      title: "List",
      value: "list"
    }

components/lists/langnav/searchlogic:
  contents:
    - showRoot: {
      title: "Show Root",
      value: "showRoot"
    }
    - hidden: {
      title: "Show Nothing",
      value: "hidden"
    }

components/lists/langnav/languageSet:
  contents:
    - en: {
      title: "EN",
      description: "English",
      value: "au/en"
    }
    - ru: {
      title: "RU",
      description: "Russian",
      value: "ru/ru"
    }

components/lists/assetlist/orderby:
  contents:
    - bytitle: {
      title: "By Title",
      value: "@jcr:content/jcr:title"
    }
    - byscore: {
      title: "By Score",
      value: "@jcr:score"
    }

components/lists/assetlist/variant:
  contents:
    - figure: {
      title: "Figure",
      value: "figure"
    }

components/lists/listnav/badge:
  contents:
    - cardHorizontalIconTitleCategoryDescriptionAction: {
      title: "Horizontal Card with Icon, Title, Category, Description and Action",
      value: "cardHorizontalIconTitleCategoryDescriptionAction"
    }
    - cardIconTitleCategoryDescriptionAction: {
      title: "Card with Icon, Title, Category, Description and Action",
      value: "cardIconTitleCategoryDescriptionAction"
    }
    - cardImageTitleCategoryDescriptionAction: {
      title: "Card with Image, Title, Category, Description and Action",
      value: "cardImageTitleCategoryDescriptionAction"
    }
