
# WARNING: Reference to these path is hardcoded into component dialogs
# /apps/aemdesign/global/dialog/touch/sitetheme
common/site/themecategory:
  prefixes:
    - none
  valueFormat: ' '
  title: '%%prefix_normalised%%'

# WARNING: Reference to these path is hardcoded into component dialogs
# /apps/aemdesign/global/dialog/touch/sitetheme
common/site/themecolor:
  prefixes:
    - none
  valueFormat: ' '
  title: '%%prefix_normalised%%'

# WARNING: Reference to these path is hardcoded into component dialogs
# /apps/aemdesign/global/dialog/touch/sitetheme
common/site/tilecolor:
  prefixes:
    - none
  valueFormat: ' '
  title: '%%prefix_normalised%%'
