
# Colctrl
layout/colctrl/flush:
  prefixes:
    - grid-flush
  prefixValue: theme--
  title: 'Grid - %%prefix_normalised%%'

layout/colctrl/column:
  prefixToFolders:
    sm: small
    md: medium
    lg: large
  prefixes:
    - sm
    - md
    - lg
  sizes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  valueFormat: 'col-%%prefix%%-%%size%%'
  title: '%%size%% Columns'

layout/colctrl/column/small/auto:
  flat: true
  prefix: col-auto
  title: 'Automatic Widths'

layout/colctrl/column/medium/auto:
  flat: true
  prefix: col-md-auto
  title: 'Automatic Widths - Medium Up'

layout/colctrl/column/large/auto:
  flat: true
  prefix: col-lg-auto
  title: 'Automatic Widths - Large Up'

layout/colctrl/row/align-items:
  breakpoints:
    - sm
    - md
    - lg
  prefixes:
    - baseline
    - center
    - end
    - start
    - stretch
  valueFormat: 'align-items%%infix%%-%%prefix%%'
  title: '%%prefix_normalised%% %%breakpoint%%'

layout/colctrl/row/direction:
  breakpoints:
    - sm
    - md
    - lg
  prefixes:
    - row
    - row-reverse
    - column
    - column-reverse
  valueFormat: 'flex%%infix%%-%%prefix%%'
  title: '%%prefix_normalised%% %%breakpoint%%'

layout/colctrl/row/justify-content:
  breakpoints:
    - sm
    - md
    - lg
  prefixes:
    - around
    - between
    - center
    - end
    - start
  valueFormat: 'justify-content%%infix%%-%%prefix%%'
  title: '%%prefix_normalised%% %%breakpoint%%'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout:
  prefixes:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
  startWith: col
  valueFormat: '%%prefix%%;colctrl-%%prefix%%c'
  title: '%%prefix_normalised%% Column'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-md-6-6:
  flat: true
  prefix: '2;col-sm-,12,12;col-md-,6,6'
  title: '2 Column (Small - 12, Medium - 6)'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-3-9:
  flat: true
  prefix: '2;col-md-,3,9'
  title: '2 Column - 3 | 9'



# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col5-2-3-2-3-2:
  flat: true
  prefix: '5;col-md-,2,3,2,3,2'
  title: '5 Column - 2 | 3 | 2 | 3 | 2'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col8-centered:
  flat: true
  prefix: 'col-md-8 mx-md-auto'
  title: '8 Column - Centered'


# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-mdlg-3-9:
  flat: true
  prefix: '2;col-md-,3,9;col-lg-,3,9'
  title: '2 Column (md+lg) - 3 | 9'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-lg-9-3:
  flat: true
  prefix: '2;col-lg-,9,3'
  title: '2 Column (lg) - 9 | 3'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-lg-6-6:
  flat: true
  prefix: '2;col-lg-,6,6'
  title: '2 Column (lg) - 6 | 6'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-8-4:
  flat: true
  prefix: '2;col-md-,8,4'
  title: '2 Column - 8 | 4'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col2-lg-4-7:
  flat: true
  prefix: '2;col-lg-,4,7;col-xl-,3,8'
  title: '2 Column (Large - 4 | 7, XLarge - 3 | 8)'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col1-mdlg-10-xl-8:
  flat: true
  prefix: '1;col-md-,10;col-lg-,10;col-xl-,8'
  title: '1 Column (Medium - 10, Large 10, XLarge - 8)'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col1-mdlg-10-xl-6:
  flat: true
  prefix: '1;col-md-,10;col-lg-,10;col-xl-,6'
  title: '1 Column (Medium - 10, Large - 10, XLarge - 6)'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col1-md-8-offset-lg-10-offest-xl-6-offest:
  flat: true
  prefix: '1;col-md-,8;offset-md-,2;col-lg-,10;offset-lg-,1;col-xl-,6;offset-xl-,3'
  title: '1 Column (Medium - 8 + offset 2, Large - 10 + offset 1, XLarge - 6 + offset 3)'

# WARNING: Reference to these path is hardcoded into component dialogs
#ONLY ADD NEW LAYOUTS AS OLD ONES CAN'T BE CHANGED ONCE USED
layout/colctrl/layout/col4-3-3-3-3:
  flat: true
  prefix: '4;col-md-,3,3,3,3'
  title: '4 Column - 3 | 3 | 3 | 3'
