---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  echo "RUNNING: yamllint..."
  yamllint .
  echo "RUNNING: ansible-lint..."
  ansible-lint .
  echo "RUNNING: autopep8..."
  autopep8 -i -r ./library/*.py .
  echo "RUNNING: flake8..."
  flake8 .
provisioner:
  name: ansible
  log: true
  options:
    vvv: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
  inventory:
    group_vars:
      all:
        service_aem_license_key: "${AEM_KEY}"
        service_aem_license_name: "${AEM_NAME}"
        service_adobe_cloud_username: "${ADOBECLOUD_USERNAME}"
        service_adobe_cloud_password: "${ADOBECLOUD_PASSWORD}"
        role_name: "${ROLE_NAME_FULL}"
platforms:
  - name: instance
    image: "aemdesign/ansible-playbook:centos7"
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/lib/systemd/systemd"}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/tmp/docker.sock
    privileged: true
    pre_build_image: true
  - name: aemtest
    image: "aemdesign/aem:6.5.0"
    command: ""
    published_ports:
      - 5502:8080
    env:
      TZ: "Australia/Sydney"
      AEM_JVM_OPTS:
        -server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true
        -Dorg.apache.felix.http.host=0.0.0.0"
      AEM_RUNMODE: "-Dsling.run.modes=author,crx3,crx3tar,dev"
    pre_build_image: true
    privileged: true
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
