---

- name: "set facts"
  set_fact:
    install_package: false
    install_package_ansible: "{{ install_package_ansible | default(false) }}"
    install_package_docker: "{{ install_package_docker | default(true) }}"
    install_package_from_local_maven: false
    package_comment: "[check params]"
    role_comment: "[aem]"
  tags:
    - always

- name: process package parameters {{ package_comment }}{{ role_comment }}
  no_log: "{{ debug_hide }}"
  debug:
    msg:
      - "file_url_username: {% if file_url_username %}set{% else %}not set{% endif %}"
      - "file_url_password: {% if file_url_password %}set{% else %}not set{% endif %}"
      - "aem_host: {{ aem_host | default('<MISSING>')  }}"
      - "aem_port: {{ aem_port | default('<MISSING>') }}"
      - "aem_username: {{ aem_username | default('<MISSING>') }}"
      - "aem_password: {% if aem_password %}set{% else %}not set{% endif %}"
      - "group_name: {{ group_name | default('<MISSING>') }}"
      - "package_name: {{ package_name | default('<MISSING>') }}"
      - "package_version: {{ package_version | default('<MISSING>') }}"
      - "package_url: {{ package_url | default('<MISSING>') }}"
      - "file_name: {{ file_name | default('<MISSING>') }}"
      - "file_override: {{ file_override | default('<MISSING>') }}"
      - "file_override_package_name: {{ file_override_package_name | default('<MISSING>') }}"
      - "simple_name: {{ simple_name | default('<MISSING>') }}"
      - "role_comment: {{ role_comment }}"
      - "install_package: {{ install_package }}"
      - "install_package_ansible: {{ install_package_ansible }}"
      - "install_package_docker: {{ install_package_docker }}"
      - "install_package_from_local_maven: {{ install_package_from_local_maven }}"
  tags:
    - always


- name: check package paramters {{ package_comment }}{{ role_comment }}
  set_fact:
    install_package: true
    install_package_docker: true
    nexus_available: false
    package_comment: "[{{ simple_name }}]"
  when:
    - aem_host is defined
    - aem_port is defined
    - aem_username is defined
    - aem_password is defined
    - group_name is defined
    - package_name is defined
    - package_version is defined
    - package_url is defined
    - file_name is defined
    - simple_name is defined
  tags:
    - always

- name: check if packages state using ansible {{ package_comment }}{{ role_comment }}
  become: false
  aem_check_package_installed:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
  register: package_exist
  ignore_errors: true
  when:
    - install_package
    - install_package_ansible
  tags:
    - aem-install-package-using-ansible


- name: check if packages state using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "is_package_installed"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
  register: package_exist
  ignore_errors: true
  when:
    - install_package
    - install_package_docker
  tags:
    - aem-install-package-using-docker


- name: skip role if package is installed {{ package_comment }}{{ role_comment }}
  set_fact:
    install_package: false
  when:
    - install_package
    - package_exist is defined
    - package_exist.failed is defined
    - not(package_exist.failed)
  tags:
    - always

- name: package already installed skipping {{ package_comment }}{{ role_comment }}
  debug:
    msg:
      - "package already installed"
      - "{{ package_exist }}"
      - "install_package: {{ install_package }}"
      - "install_package_ansible: {{ install_package_ansible }}"
      - "install_package_docker: {{ install_package_docker }}"
  when:
    - not install_package
  tags:
    - always

- name: installing package {{ package_comment }}{{ role_comment }}
  debug:
    msg:
      - "package is not installed"
      - "install_package: {{ install_package }}"
      - "install_package_ansible: {{ install_package_ansible }}"
      - "install_package_docker: {{ install_package_docker }}"
  when:
    - install_package
  tags:
    - always

- name: check if nexus is available {{ package_comment }}{{ role_comment }}
  uri:
    url: "{{ maven_repository_url }}"
    timeout: 3
  register: nexus_ping
  ignore_errors: true
  when:
    - install_package
    - maven_repository_url | length > 0
  tags:
    - always

- name: nexus is not available {{ package_comment }}{{ role_comment }}
  set_fact:
    nexus_available: false
    install_package_from_local_maven: false
  when:
    - install_package
    - maven_repository_url | length > 0
    - nexus_ping.status != 200
  tags:
    - always

- name: nexus registry is available {{ package_comment }}{{ role_comment }}
  set_fact:
    nexus_available: true
    local_package_maven_url: "{{ maven_repository_url }}/aemdesign/{{ package_name }}/{{ package_version }}/{{ file_name }}"
  when:
    - install_package
    - maven_repository_url | length > 0
    - nexus_ping.status == 200
  tags:
    - always

- name: create temp dir {{ package_comment }}{{ role_comment }}
  tempfile:
    state: directory
  register: tempfile
  no_log: "{{ debug_hide }}"
  when:
    - install_package
  tags:
    - always

- name: use temp dir {{ package_comment }}{{ role_comment }}
  set_fact:
    role_files_dir: "{{ tempfile.path }}"
  when:
    - install_package
  tags:
    - always

- name: check in local nexus {{ package_comment }}{{ role_comment }}
  uri:
    method: HEAD
    url: "{{ local_package_maven_url }}"
    status_code: 200
  register: nexus_check
  ignore_errors: true
  no_log: "{{ debug_hide }}"
  when:
    - install_package
    - nexus_available
  tags:
    - always

- name: package in local nexus {{ package_comment }}{{ role_comment }}
  set_fact:
    install_package_from_local_maven: true
  when:
    - install_package
    - nexus_available
    - nexus_check.status == 200
  tags:
    - always

- name: package is not in local nexus {{ package_comment }}{{ role_comment }}
  set_fact:
    install_package_from_local_maven: false
  when:
    - install_package
    - nexus_available
    - nexus_check.status == 404
  tags:
    - always

- name: get from local nexus {{ package_comment }}{{ role_comment }}
  uri:
    url: "{{ local_package_maven_url }}"
    dest: "{{ role_files_dir }}/{{ file_name }}"
    status_code: 200
  register: download_package
  ignore_errors: true
  when:
    - install_package
    - nexus_available
    - install_package_from_local_maven
  tags:
    - always

- name: download file {{ package_comment }}{{ role_comment }}
  get_url:
    url: "{{ package_url }}"
    dest: "{{ role_files_dir }}/{{ file_name }}"
    url_username: "{{ file_url_username }}"
    url_password: "{{ file_url_password }}"
  register: download_package
  when:
    - install_package
    - install_package_ansible
    - not install_package_from_local_maven
  tags:
    - always

- name: upload to maven {{ package_comment }}{{ role_comment }}
  uri:
    url: "{{ local_package_maven_url }}"
    user: "{{ maven_repository_username }}"
    password: "{{ maven_repository_password }}"
    method: PUT
    src: "{{ role_files_dir }}/{{ file_name }}"
  when:
    - install_package
    - nexus_available
    - not install_package_from_local_maven
  tags:
    - always

- name: upload package to aem using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    file_path: "{{ role_files_dir }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "upload_package_sync"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
    file_url: "{{ package_url }}"
    file_name: "{{ file_name }}"
    file_url_password: "{{ file_url_password | default('') }}"
    file_url_username: "{{ file_url_username | default('') }}"
  register: result
  until: result is success
  retries: 1
  delay: 0
  when:
    - install_package
    - install_package_docker
    - file_override is not defined or not(file_override)

- name: upload package to aem using ansible {{ package_comment }}{{ role_comment }}
  aem_upload_package:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    file_path: "{{ role_files_dir }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_ansible
    - file_override is not defined or not(file_override)
  tags:
    - aem-install-package-using-ansible

- name: upload package to aem override filename using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ file_override_package_name }}"
    package_version: "{{ package_version }}"
    file_path: "{{ role_files_dir }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "upload_package_sync"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_docker
    - file_override is defined and file_override

- name: verify package uploaded using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "is_package_uploaded"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
  register: result
  until: result is success
  retries: 1
  delay: 0
  when:
    - install_package
    - install_package_docker
  tags:
    - aem-install-package-using-docker


- name: verify package uploaded using ansible {{ package_comment }}{{ role_comment }}
  aem_check_package_uploaded:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_ansible
  tags:
    - aem-install-package-using-ansible


- name: install package using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "install_package_sync"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_docker


- name: install package using ansible {{ package_comment }}{{ role_comment }}
  aem_install_package:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_ansible
  tags:
    - aem-install-package-using-ansible


- name: wait for packages installed completed {{ package_comment }}{{ role_comment }}
  include_role:
    name: aem_design.aem_verify
  when:
    - install_package
  tags:
    - always

- name: ensure packages installed using docker {{ package_comment }}{{ role_comment }}
  become: true
  pyaem_command:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
    api_command: "is_package_installed"
    docker_host: "{{ docker_host | default('unix://var/run/docker.sock') }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_docker

- name: ensure packages installed using ansible {{ package_comment }}{{ role_comment }}
  become: false
  aem_check_package_installed:
    host: "{{ aem_host }}"
    port: "{{ aem_port }}"
    group_name: "{{ group_name }}"
    package_name: "{{ package_name }}"
    package_version: "{{ package_version }}"
    aem_username: "{{ aem_username }}"
    aem_password: "{{ aem_password }}"
  register: result
  until: result is success
  retries: 180
  delay: 5
  when:
    - install_package
    - install_package_ansible
  tags:
    - aem-install-package-using-ansible

- name: removing temp directory {{ role_comment | default('') }}
  file:
    name: "{{ tempfile.path }}"
    state: absent
  become: true
  become_method: sudo
  when:
    - install_package
    - tempfile is defined
    - tempfile.path is defined
