name: ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        java-version: [ 11 ]
        python-version: [ 3.6 ]

    env:
      DOCKER_IMAGE: "aemdesign/centos-java-buildpack:jdk11"
      SONAR_ORGANISATION: "aemdesign-github"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_URL: "https://sonarcloud.io"
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: "aemdesign"
      GITHUB_USER: aemdesign
      TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
      GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      GITHUB_TOKEN_ADMIN: ${{ secrets.GITHUB_TOKEN_ADMIN }}
      AEM_NAME: ${{ secrets.AEM_NAME }}
      AEM_KEY: ${{ secrets.AEM_KEY }}
      GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_EXECUTABLE: gpg
      GPG_PRESET_EXECUTABLE: /usr/lib/gnupg/gpg-preset-passphrase
      GPG_PUBID: "50A036956AAC64C13EF47B10D1E96A30ECFC7DFF"
      GPG_PUBID_KEYGRIP: "020E615868703482DC2CD110B98D2702B6ABF89C"
      PERSONAL_ADMIN_TOKEN: ${{ secrets.PERSONAL_ADMIN_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up jdk ${{ matrix.java-version }}
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ matrix.java-version }}

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '10.x'
          registry-url: https://npm.pkg.github.com/
          scope: "@aem-design"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_ADMIN }}
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get release notes
        id: config
        run: |
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/github_get_version.sh)

      - name: Output release notes
        run: |
          echo "${{ steps.config.outputs.GIT_RELEASE_NOTES }}"
          echo CURRENT_VERSION="${{ steps.config.outputs.CURRENT_VERSION }}"

      - name: Set eval variables
        run: |
          echo "DOCKER_COMMAND=docker run --user $(id -u):$(id -g) -v ${GITHUB_WORKSPACE}:/build -v /home/runner/.m2:/build/.m2 ${DOCKER_IMAGE}" >> $GITHUB_ENV
          $DOCKER_COMMAND java -version
          $DOCKER_COMMAND node -v
          git config --global user.email "${GITHUB_EMAIL}"
          git config --global user.name "${GITHUB_USERNAME}"

      - name: Setup gpg
        run: |
          source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/setup-gpg.sh)

      - name: Cache sonarcloud packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Prepare to Package
        run: $DOCKER_COMMAND mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -P all-modules -Dmaven.repo.local=/build/.m2/repository

      - name: Package project and install into local .m2 repository
        run: $DOCKER_COMMAND mvn package install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -P all-modules -Dmaven.repo.local=/build/.m2/repository

      - name: Start the stack
        run: |
          docker-compose up -d

      - name: Wait for aem using ansible
        run: |
          docker ps
          ls ~/.m2
          ls /home/runner/.m2
          docker-compose up automationtestprep

      - name: Start automation tests using docker-compose
        run: |
          docker-compose up automationtest

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ADMIN_TOKEN }}
          destination_dir: ${{ env.GIT_BRANCH }}
          publish_dir: ./aemdesign-testing/remote-seleniumhub-chrome/generated-docs/html/
          enable_jekyll: true
          external_repository: aem-design/aemdesign-aem-support-output

      # - name: Check for success
      #   run: |
      #     docker-compose up testingcheck

      - name: Stop the stack
        run: docker-compose down

#      - name: docker - sonar qube on master
#        if: github.ref == 'refs/heads/master'
#        run: mvn sonar:sonar -P all-modules -q "-Dsonar.branch.name=${GITHUB_REF}" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}"
#      - name: docker - sonar qube on master
#        if: github.ref != 'refs/heads/master'
#        run: mvn sonar:sonar -P all-modules -q "-Dsonar.branch.name=${GITHUB_REF}" "-Dsonar.branch.target=master" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}"

      - name: Deploy to maven cental
        if: github.ref == 'refs/heads/master'
        run: $DOCKER_COMMAND echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import && echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust && mvn deploy --settings default.xml -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -DskipTests=true -B -P release

      - name: Create release ${{ env.GITHUB_TAG }}
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.config.outputs.CURRENT_VERSION }}
          release_name: ${{ steps.config.outputs.CURRENT_VERSION }}
          body: ${{ steps.config.outputs.GIT_RELEASE_NOTES }}
          draft: false
          prerelease: false

      - name: Upload release asset - aemdesign-aem-support-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'support-deploy', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'support-deploy', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Upload release asset - aemdesign-aem-compose-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'compose', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'compose', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Upload release asset - aemdesign-aem-showcase-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'showcase', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'showcase', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Upload release asset - aemdesign-aem-training-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'training', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'training', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Upload release asset - aemdesign-aem-content-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'content', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'content', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Upload release asset - aemdesign-aem-config-${{ env.GITHUB_TAG }}.zip
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ format('./aemdesign-aem-{0}/target/aemdesign-aem-{0}-{1}.zip', 'config', env.GITHUB_TAG) }}
          asset_name: ${{ format('aemdesign-aem-{0}-{1}.zip', 'config', env.GITHUB_TAG) }}
          asset_content_type: application/zip

      - name: Automation test if failure
        run: |
          df
          docker ps -a
          docker-compose down
        if: failure()

