name: ci

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v1
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: set variables
        run: |
          echo $HOME
          export BUILD_IMAGE="aemdesign/centos-java-buildpack"
          export MAVEN_DIR=$HOME/.m2
          ls $HOME
#      - name: docker - mvn clean
#        run: docker run --user $(id -u):$(id -g) -v $HOME:/build -w "/build/${PARENT_PROJECT_NAME}/${PARENT_PROJECT_LOCATION}" -v ${MAVEN_DIR}:/build/.m2 $BUILD_IMAGE mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -P all-modules -q && echo "CLEAN DONE"
