name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    env:
      BUILD_IMAGE: aemdesign/centos-java-buildpack

    steps:
      - uses: actions/checkout@v1
      - name: docker - mvn clean and cache .m2 in ./build/.m2/repository in repo dir
        run: docker run --user $(id -u):$(id -g) -v $GITHUB_WORKSPACE:/build $BUILD_IMAGE mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -P all-modules -q -Dmaven.repo.local=./build/.m2/repository
