name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          lfs: true
      - name: mirror repo to azure
        run: |
          git checkout master
          git config lfs.https://aemdesign@dev.azure.com/aemdesign/AEM.Design/_git/aemdesign-aem-support.git/info/lfs.locksverify=true
          git push --mirror https://aemdesign:${AZURE_TOKEN}@dev.azure.com/aemdesign/AEM.Design/_git/aemdesign-aem-support
